name: Docker Build and Run

on: 
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Create environment file
        run: echo "export API_KEY_GEO=${{ secrets.API_KEY_GEO }}" >> .env
        
      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t jawadzd/speedshop:latest .

      # Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push jawadzd/speedshop:latest

      # Run the Docker container
      - name: Run Docker Container
        run: docker run -d --name my-container -p 80:80 jawadzd/speedshop:latest
